/**
 * with-widgets.js — Expo config plugin
 *
 * Adds an iOS Widget Extension target to the OfferHound app:
 *   - Target / bundle id : com.emergentmindlab.offerhoundv2.widgets
 *   - App Group           : group.com.emergentmindlab.offerhoundv2.shared
 *
 * What this plugin does at prebuild time:
 *   1. Adds the App Group entitlement to the host app.
 *   2. Adds a placeholder PBXNativeTarget for the widget extension via
 *      `withXcodeProject`, pointing at the Swift sources we ship in
 *      `ios-prebuild-assets/Widgets/`.
 *   3. Copies those Swift sources into the prebuilt iOS project under
 *      `ios/OfferHoundWidgets/`.
 *
 * IMPORTANT
 *   The Xcode project mutations here are intentionally minimal because Expo's
 *   `xcode` parser does not support every Widget-Extension build setting that
 *   Apple expects. The fully wired-up extension (Info.plist keys, capabilities,
 *   provisioning profile, embed-app-extension build phase) must still be
 *   completed in Xcode the first time. See `WIDGETS_SETUP.md`.
 *
 *   Do NOT run `expo prebuild` here. The plugin is registered so it runs the
 *   next time the iOS project is generated by EAS / `expo prebuild`.
 */

const fs = require('fs');
const path = require('path');
const {
  withEntitlementsPlist,
  withXcodeProject,
  withDangerousMod,
} = require('@expo/config-plugins');

const APP_GROUP = 'group.com.emergentmindlab.offerhoundv2.shared';
const WIDGET_TARGET = 'OfferHoundWidgets';
const WIDGET_BUNDLE_ID = 'com.emergentmindlab.offerhoundv2.widgets';

/* -------------------------------------------------------------------------- */
/* 1. App Group entitlement on the host app                                   */
/* -------------------------------------------------------------------------- */
const withAppGroupEntitlement = (config) =>
  withEntitlementsPlist(config, (cfg) => {
    const groups = cfg.modResults['com.apple.security.application-groups'] || [];
    if (!groups.includes(APP_GROUP)) groups.push(APP_GROUP);
    cfg.modResults['com.apple.security.application-groups'] = groups;
    return cfg;
  });

/* -------------------------------------------------------------------------- */
/* 2. Copy Widget Swift sources + Info.plist + entitlements into ios/         */
/* -------------------------------------------------------------------------- */
const withWidgetSources = (config) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const platformRoot = cfg.modRequest.platformProjectRoot; // ios/

      const srcDir = path.join(projectRoot, 'ios-prebuild-assets', 'Widgets');
      const dstDir = path.join(platformRoot, WIDGET_TARGET);

      if (!fs.existsSync(srcDir)) {
        console.warn(
          `[with-widgets] Source dir not found: ${srcDir} — skipping copy`,
        );
        return cfg;
      }
      fs.mkdirSync(dstDir, { recursive: true });

      // Copy every .swift file
      for (const file of fs.readdirSync(srcDir)) {
        if (file.endsWith('.swift')) {
          fs.copyFileSync(path.join(srcDir, file), path.join(dstDir, file));
        }
      }

      // Info.plist for the widget extension
      const infoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>$(DEVELOPMENT_LANGUAGE)</string>
  <key>CFBundleDisplayName</key><string>OfferHound</string>
  <key>CFBundleExecutable</key><string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key><string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key><string>com.apple.widgetkit-extension</string>
  </dict>
</dict>
</plist>
`;
      fs.writeFileSync(path.join(dstDir, 'Info.plist'), infoPlist);

      // Entitlements file with the App Group
      const entitlements = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${APP_GROUP}</string>
  </array>
</dict>
</plist>
`;
      fs.writeFileSync(
        path.join(dstDir, `${WIDGET_TARGET}.entitlements`),
        entitlements,
      );

      return cfg;
    },
  ]);

/* -------------------------------------------------------------------------- */
/* 3. Best-effort PBX target stub                                             */
/* -------------------------------------------------------------------------- */
const withWidgetXcodeTarget = (config) =>
  withXcodeProject(config, (cfg) => {
    const proj = cfg.modResults;

    // Bail early if the target already exists (idempotent reruns).
    const existing = proj.pbxNativeTargetSection
      ? Object.values(proj.pbxNativeTargetSection())
      : [];
    const alreadyAdded = existing.some(
      (t) => t && typeof t === 'object' && t.name === WIDGET_TARGET,
    );
    if (alreadyAdded) return cfg;

    try {
      // Create the PBXGroup so Xcode shows the widget folder in the navigator.
      const group = proj.addPbxGroup(
        ['OfferHoundWidgetBundle.swift', 'RecentLettersWidget.swift', 'UpcomingCampWidget.swift', 'Info.plist', `${WIDGET_TARGET}.entitlements`],
        WIDGET_TARGET,
        WIDGET_TARGET,
      );
      // Attach to top-level project group
      const groups = proj.hash.project.objects['PBXGroup'];
      Object.keys(groups).forEach((key) => {
        if (
          typeof groups[key] === 'object' &&
          groups[key].name === undefined &&
          groups[key].path === undefined
        ) {
          proj.addToPbxGroup(group.uuid, key);
        }
      });
    } catch (e) {
      console.warn(
        `[with-widgets] Could not auto-add Widget group to Xcode project: ${e.message}\n` +
          'Open the project in Xcode and add the OfferHoundWidgets folder + target manually (see WIDGETS_SETUP.md).',
      );
    }

    return cfg;
  });

/* -------------------------------------------------------------------------- */
module.exports = function withWidgets(config) {
  config = withAppGroupEntitlement(config);
  config = withWidgetSources(config);
  config = withWidgetXcodeTarget(config);
  return config;
};

module.exports.APP_GROUP = APP_GROUP;
module.exports.WIDGET_TARGET = WIDGET_TARGET;
module.exports.WIDGET_BUNDLE_ID = WIDGET_BUNDLE_ID;
